// Generated by CoffeeScript 1.6.3
(function() {
  var Airport;

  Airport = (function() {
    function Airport(city, code, travelers, planes) {
      this.city = city;
      this.code = code;
      this.travelers = travelers != null ? travelers : [];
      this.planes = planes != null ? planes : [];
    }

    return Airport;

  })();

  module.exports = Airport;

}).call(this);
