// Generated by CoffeeScript 1.6.3
(function() {
  var Crew, Person,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Person = require("./person");

  Crew = (function(_super) {
    __extends(Crew, _super);

    function Crew(name, age, weight, title) {
      this.name = name;
      this.age = age;
      this.weight = weight;
      this.title = title;
      Crew.__super__.constructor.call(this, this.name, this.age, this.weight);
    }

    return Crew;

  })(Person);

  module.exports = Crew;

}).call(this);
