// Generated by CoffeeScript 1.6.3
(function() {
  var Passenger, Person,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Person = require("./person");

  Passenger = (function(_super) {
    __extends(Passenger, _super);

    function Passenger(name, age, weight, destination) {
      this.name = name;
      this.age = age;
      this.weight = weight;
      this.destination = destination;
      Passenger.__super__.constructor.call(this, this.name, this.age, this.weight);
    }

    return Passenger;

  })(Person);

  module.exports = Passenger;

}).call(this);
