// Generated by CoffeeScript 1.6.3
(function() {
  var Person;

  Person = (function() {
    function Person(name, age, weight) {
      this.name = name;
      this.age = age;
      this.weight = weight;
    }

    return Person;

  })();

  module.exports = Person;

}).call(this);
